name: Website Monitor

on:
  schedule:
    - cron: '*/15 * * * *'  # every 15 minutes
  workflow_dispatch:

jobs:
  run-monitor:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4 twilio

    - name: Run monitor
      env:
        TWILIO_SID: ${{ secrets.TWILIO_SID }}
        TWILIO_AUTH: ${{ secrets.TWILIO_AUTH }}
        TWILIO_FROM: ${{ secrets.TWILIO_FROM }}
        TWILIO_TO: ${{ secrets.TWILIO_TO }}
      run: python monitor.py
